accountapp/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('onlymember/', views.only_member, name="onlymember"),
]

fifthapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('createTodo/', views.createTodo, name='createTodo'),
    path('deleteTodo/', views.deleteTodo, name='deleteTodo'),
]

studyproject/urls.py
from django.contrib import admin
from django.urls import path,include
import firstapp.views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/',firstapp.views.welcome),
    path('secondapp/',include('secondapp.urls')),
    path('mydjango/myname/',firstapp.views.getname),
    path('forthapp/',include('forthapp.urls')),
    path('fifthapp/',include('fifthapp.urls')),
    path('uploadapp/',include('uploadapp.urls')),
    path('redirectapp/',include('redirectapp.urls')),
    path('visitorapp/',include('visitorapp.urls')),
    path('relationapp/',include('relationapp.urls')),
    path('accountapp/',include('accountapp.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

def index(request) :
    context = None
    print(request.user.is_authenticated)
    print(request.user)
    if request.user.is_authenticated:
        context = {'logineduser': request.user}
    return render(request, 'index.html', context)

def register(request):
    res_data = None
    if request.method =='POST':
        useremail = request.POST.get('useremail')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        password = request.POST.get('password')
        re_password = request.POST.get('re-password')
        res_data = {}
        if User.objects.filter(username=useremail):
            res_data['error']='이미 가입된 아이디(이메일주소)입니다.'
        elif password != re_password:
            res_data['error']='비밀번호가 다릅니다.'
        else:
            user = User.objects.create_user(username = useremail,
                            first_name = firstname,
                            last_name = lastname,
                            password = password)
            auth.login(request, user)
            redirect("index.html")
    return render(request, 'register.html', res_data)  # 교육생들 수정!!!!


def login(request):
    if request.method == "POST":
        useremail = request.POST.get('useremail', None)
        password = request.POST.get('password', None)
        user = auth.authenticate(username=useremail, password=password)
        #print("***", user.date_joined)
        if user is not None :
            auth.login(request, user)
            return redirect("account:index")
        else :
            return render(request, 'login.html', {'error': '사용자 아이디 또는 패스워드가 틀립니다.'})
    else :
        return render(request, 'login.html')

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
    return redirect("account:index")

def only_member(request) :
    context = None
    if request.user.is_authenticated:
        context = {'logineduser': request.user.last_name+request.user.first_name}
    return render(request, 'member.html', context)

accountapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul>
     <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Dropdown link
      </a>
      <div class="dropdown-menu">
        {% if not logineduser %}
            <a class="dropdown-item" href="{% url 'account:register' %}">회원가입</a>
            <a class="dropdown-item" href="{% url 'account:login' %}">로그인</a>
        {% else %}
            <a class="dropdown-item" href="{% url 'account:logout' %}">로그아웃</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'account:onlymember' %}">회원페이지</a>
      </div>
    </li>
  </ul>
</nav>
{% endblock %}

accountapp/templates/login.html
{% extends "base.html" %}
{% block content %}
{% if msg  %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>{{msg}}</h1>
        </div>
    </div>
{% else %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>로그인</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12 text-center" style="color:red">
         {{error}}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action="{% url 'account:login'%}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="username">사용자 아이디</label>
                 <input type="text" class="form-control"  name="useremail" placeholder="사용자 아이디" >
              </div>
                <div class="form-group">
                   <label for="password">비밀번호</label>
                   <input type="password" class="form-control" name="password" placeholder="비밀번호" >
                </div>
                <button type="submit" class="btn btn-primary">로그인</button>
            </form>
        </div>
    </div>
{% endif %}
<div class="col-12 text-center">
    <a href="{% url 'account:index' %}">메인화면으로</a>
</div>
{% endblock %}

accountapp/templates/logout.html
{% extends "base.html" %}
{% block content %}
<div class="row mt-5">
    <div class="col-12 text-center" style="color:green">
        <h1>{{ msg }}</h1>
    </div>
</div>
<div class="col-12 text-center">
        <a href="{% url 'account:index' %}">메인화면으로</a>
</div>
{% endblock %}

accountapp/templates/member.html
{% extends "base.html" %}
{% block content %}
<div class="row mt-5">
    <div class="col-12 text-center">
        {% if not logineduser %}
            <h3>로그인을 하지 않았으므로 이페이지를 볼 수 없습니다!! 로그인하세요!!</h3>
        {% else %}
            <h3>로그인을 했으므로 이페이지를 볼 수 있습니다!! {{ logineduser }}님!!</h3>
        {% endif %}
    </div>
     <div class="col-12 text-center">
        <a href="{% url 'account:index' %}">메인화면으로</a>
    </div>
</div>
{% endblock %}

accountapp/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
            <div class="row mt-5">
                <div class="col-12 text-center">
                    <h1>회원가입</h1>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12 text-center" style="color:red">
                    {{error}}
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12">
                    <form method="POST" action="{% url 'account:register' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="useremail">사용자 이메일</label>
                            <input type="email" class="form-control"  placeholder="사용자 아이디" name="useremail" required>
                            <small id="emailHelp" class="form-text text-muted">이메일 주소를 아이디로 사용합니다.</small>
                        </div>
                        <div class="form-group">
                            <label for="username">사용자 성과 이름</label>
                            <input type="text" class="form-control"  placeholder="성" name="lastname" required>
                            <input type="text" class="form-control"  placeholder="이름" name="firstname" required>
                        </div>
                        <div class="form-group">
                            <label for="password">비밀번호</label>
                            <input type="password" class="form-control" placeholder="비밀번호" name="password" required>
                        </div>
                        <div class="form-group">
                            <label for="re-password">비밀번호 확인</label>
                            <input type="password" class="form-control" placeholder="비밀번호 확인" name="re-password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">회원가입</button>
                    </form>
                </div>
            </div>
            <div class="col-12 text-center">
            <a href="{% url 'account:index' %}">메인화면으로</a>
            </div>
     </div>
{% endblock %}